/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    CabeceraPorDefecto: typeof import('./src/components/lazy/CabeceraPorDefecto.vue')['default']
    Card: typeof import('primevue/card')['default']
    CellAccionesUsuario: typeof import('./src/components/lazy/usuarios/CellAccionesUsuario.vue')['default']
    CellActivoUsuario: typeof import('./src/components/lazy/usuarios/CellActivoUsuario.vue')['default']
    Chip: typeof import('primevue/chip')['default']
    Column: typeof import('primevue/column')['default']
    ContenidoPorDefecto: typeof import('./src/components/lazy/ContenidoPorDefecto.vue')['default']
    CrearPermiso: typeof import('./src/components/permisos/CrearPermiso.vue')['default']
    CrearUsuario: typeof import('./src/components/usuarios/CrearUsuario.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    EditarPermiso: typeof import('./src/components/permisos/EditarPermiso.vue')['default']
    EditarUsuarios: typeof import('./src/components/usuarios/EditarUsuarios.vue')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FiltrosPermisos: typeof import('./src/components/permisos/FiltrosPermisos.vue')['default']
    FiltrosUsuarios: typeof import('./src/components/usuarios/FiltrosUsuarios.vue')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Password: typeof import('primevue/password')['default']
    PlantillaBase: typeof import('./src/components/PlantillaBase.vue')['default']
    PlantillaBaseCentrada: typeof import('./src/components/PlantillaBaseCentrada.vue')['default']
    Popover: typeof import('primevue/popover')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    TablaPermisos: typeof import('./src/components/permisos/TablaPermisos.vue')['default']
    TablaUsuarios: typeof import('./src/components/usuarios/TablaUsuarios.vue')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
    Tag: typeof import('primevue/tag')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
